//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ksiazka()
        {
            this.WypozyczenieKsiazki = new HashSet<WypozyczenieKsiazki>();
        }
    
        public int IdKsiazki { get; set; }
        public string TytulKsiazki { get; set; }
        public string Sygnatura { get; set; }
        public int AutorKluczObcyId { get; set; }
        public bool CZyKsiazkaWypozyczona { get; set; }
    
        public virtual AutorKsiazki AutorKsiazki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieKsiazki> WypozyczenieKsiazki { get; set; }
    }
}
