//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaBazaEntities : DbContext
    {
        public BibliotekaBazaEntities()
            : base("name=BibliotekaBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutorKsiazki> AutorKsiazki { get; set; }
        public virtual DbSet<Czytelnik> Czytelnik { get; set; }
        public virtual DbSet<Ksiazka> Ksiazka { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<WypozyczenieKsiazki> WypozyczenieKsiazki { get; set; }
    }
}
